# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build udohbe-frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          NEXT_PUBLIC_API_KEY: 630a711b33ad2167751aeee5
          NEXT_PUBLIC_BEARER_TOKEN: 989ae6b9daf77172b12cf6ed778a94da5d53629665975f2443e12449b4cfe501f7a978c4fccda7a1542fb12123b4ef914e5275505948e6e4a9e985205b37fccb4ec7248708dabb05a68c3f1e52f6328cfe12f2587a7f29d9f20c6b72bbb9031bdeb652ac7a4871c39a8ebc5952003689458f460affc61e902b4951f3b9520fab
          NEXT_PUBLIC_MARCHANT_KEY:  PZ78-PKLIVE-D8F76467-0C0A-43C7-A055-44B2EE7C6952
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 10c304ea-899b-42f6-b0e7-8705ff494335
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/udohbe-frontend/config.yaml
          action: upload
